services:
  dashboard:
    container_name: dashboard
    build: .
    restart: unless-stopped
    ports:
      - "3005:3000"
    volumes:
      - ./public:/app/public
      - ./server.js:/app/server.js
    env_file:
      - .env
    environment:
      - NODE_ENV=production